version: "3.8"

services:
  httpserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9989:9989
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: vit
      POSTGRES_PASSWORD: p!ssword2717
      POSTGRES_DB: market
    ports:
      - 5432:5432
